/** Tags shown in feed filter (display casing) */
export const FEED_TAGS = [
  "All",
  "LostItem",
  "UrgentHelp",
  "Found",
  "Guidance",
  "Donation",
  "Medical",
  "Financial",
  "Other",
];

/** Lowercase tokens for keyword / tag suggestion matching */
export const TAG_SUGGESTION_LEXICON = [
  ...FEED_TAGS.filter((t) => t !== "All").map((t) => t.toLowerCase()),
  "plumbing",
  "electrical",
  "gardening",
  "carpentry",
  "emergency",
  "it-support",
  "cooking",
  "cleaning",
  "painting",
  "auto-repair",
  "tutoring",
  "babysitting",
  "pet-care",
  "furniture-assembly",
  "moving-help",
  "food",
  "water",
  "flood",
  "fire",
  "injury",
  "hospital",
  "money",
  "rent",
  "transport",
  "elderly",
  "child",
  "lost",
  "found",
  "animal",
];
